name: 'Configuration Provider'
type: module
description: 'Enables provision of configuration by extensions.'
core_version_requirement: ^9.3 || ^10 || ^11
container_rebuild_required: true
package: Configuration
dependencies:
  - 'drupal:config'

# Information added by Drupal.org packaging script on 2025-08-12
version: '3.0.0-alpha3'
project: 'config_provider'
datestamp: 1755033599
