backstop_generator.viewport.*:
  type: config_entity
  label: Backstop Viewport
  mapping:
    id:
      type: string
      label: ID
    label:
      type: label
      label: Label
    uuid:
      type: string
    description:
      type: string
    height:
      type: integer
      label: Height
    width:
      type: integer
      label: Width
