backstop_generator.settings:
  type: config_entity
  label: Backstop Settings
  mapping:
    uuid:
      type: string
    backstop_directory:
      type: string
      label: Backstop Directory
    test_domain:
      type: string
      label: Test Domain
    reference_domain:
      type: string
      label: Reference Domain
    scenarioDefaults:
      type: mapping
      label: Scenario defaults
      mapping:
        delay:
          type: integer
          label: delay
        hideSelectors:
          type: string
          label: hideSelectors
        removeSelectors:
          type: string
          label: removeSelectors
        misMatchThreshold:
          type: decimal
          label: misMatchThreshold
        requireSameDimensions:
          type: boolean
          label: requireSameDimensions
        cookiePath:
          type: string
          label: cookiePath
        readyEvent:
          type: string
          label: readyEvent
        readySelector:
          type: string
          label: readySelector
        readyTimeout:
          type: integer
          label: readyTimeout
        onReadyScript:
          type: boolean
          label: onReadyScript
        onBeforeScript:
          type: boolean
          label: onBeforeScript
        keyPressSelectors:
          type: string
          label: keyPressSelectors
        hoverSelector:
          type: string
          label: hoverSelector
        hoverSelectors:
          type: string
          label: hoverSelectors
        clickSelector:
          type: string
          label: clickSelector
        clickSelectors:
          type: string
          label: clickSelectors
        postInteractionWait:
          type: integer
          label: postInteractionWait
        scrollToSelector:
          type: string
          label: scrollToSelector
        selectors:
          type: string
          label: selectors
        selectorExpansion:
          type: boolean
          label: selectorExpansion
        expect:
          type: integer
          label: expect
        gotoParameters:
          type: string
          label: gotoParameters
    profile_parameters:
      type: mapping
      label: Profile parameters
      mapping:
        onBeforeScript:
          type: boolean
          label: onBeforeScript
        paths:
          type: string
          label: paths
        report:
          type: string
          label: report
        asyncCaptureLimit:
          type: integer
          label: asyncCaptureLimit
        asyncCompareLimit:
          type: integer
          label: asyncCompareLimit
        engine:
          type: string
          label: engine
        engineOptions:
          type: string
          label: engineOptions
