patreon.settings:
  type: config_object
  label: 'Patreon settings'
  mapping:
    patreon_client_id:
      type: string
      label: 'The Patreon client ID'
    patreon_client_secret:
      type: string
      label: 'The Patreon client secret'