artisan.settings:
  type: theme_settings
  label: 'Artisan settings'
  mapping:
    vite_dev_host:
      type: string
    vite_dev_port:
      type: integer
    customizations:
      type: boolean
    fonts:
      type: text
    properties:
      type: text
