config_patch.settings:
  type: config_object
  label: 'Config patch settings'
  mapping:
    config_base_path:
      type: string
      label: 'Config base path for patch'
    output_plugin:
      type: string
      label: 'Output plugin'

