path_alias_class.settings:
  type: config_object
  label: 'Path Alias Class Settings'
  mapping:
    add_path:
      type: boolean
      label: 'Add Path'
    add_alias:
      type: boolean
      label: 'Add Alias'
    add_class:
      type: string
      label: 'Add Custom Class'