# Schema for the configuration files of the CKEditor5 module.
ckeditor5_markdown_editor.settings:
  type: config_object
  label: Configuration of the module
  mapping:
    ckeditor_version:
      type: string
      label: CKEditor version detected
    plugins_version_installed:
      type: string
      label: CKEditor markdown plugin version detected


# Plugin \Drupal\ckeditor5_markdown_editor\Plugin\CKEditor5Plugin\MarkdownOutputSettings
ckeditor5.plugin.ckeditor5_markdown_editor_markdown_gfm:
  type: mapping
  label: Markdown
  mapping:
    markdown_output:
      type: boolean
      label: 'Markdown'
