alt_login.settings:
  type: config_object
  label: 'Alternative login settings'
  mapping:
    display:
      type: string
      label: Display name
    display_anon:
      #this should be translatable
      type: text
      label: Name as it appears to anon.
    aliases:
      type: sequence
      label: Login options
      sequence:
        - type: string
          label: Login option
    name_mode: 
      type: string
      label: Name mode
    login: 
      type: sequence
      label: Login options
