# Schema for configuration files of the Cookie Information module.

cookieinformation.settings:
  type: config_object
  label: 'Cookie Information settings'
  mapping:
    enable_popup:
      type: boolean
      label: 'Enable the cookie consent popup.'
    google_consent_mode:
      type: string
      label: 'Google Consent Mode'
    block_iframes:
      type: boolean
      label: 'Block iframes unless consent has been given'
    block_iframes_category:
      type: string
      label: 'Cookie category to block iframes by'
    enable_iab:
      type: boolean
      label: 'Enable the IAB cookie consent popup.'
    exclude_paths:
      type: string
      label: 'Exclude paths.'
    exclude_admin:
      type: boolean
      label: 'Exclude admin routes.'
    exclude_uid_1:
      type: boolean
      label: 'Exclude user 1.'
