patreon_user.settings:
  type: config_object
  label: 'Patreon user settings'
  mapping:
    patreon_user_registration:
      type: integer
      label: 'The Patreon user registration option'
    patreon_user_login_method:
      type: integer
      label: 'The Patreon user login method'