logo_image_enhanced.settings:
  type: config_object
  label: 'Logo Image Style settings'
  mapping:
    logo_style:
      type: string
      label: 'Image style for logo'
    logo_path:
      type: string
      label: 'Logo path'
    logo_alt:
      type: string
      label: 'Logo alt text'
    logo_title:
      type: string
      label: 'Logo title attribute'