entityqueue_buttons.settings:
  type: config_object
  label: 'EntityQueue Buttons settings'
  mapping:
    queue_settings:
      type: mapping
      label: 'Queue settings per content type'
      mapping:
        '[content_type]':
          type: sequence
          label: 'Enabled queues'
          sequence:
            type: string
            label: 'Queue ID'