config.patch:
  path: '/admin/config/development/configuration/patch'
  defaults:
    _form: '\Drupal\config_patch\Form\ConfigPatch'
    _title: 'Patch'
  requirements:
    _permission: 'export configuration'

config.patch_per_plugin:
  path: '/admin/config/development/configuration/patch/{plugin_id}'
  defaults:
    _form: '\Drupal\config_patch\Form\ConfigPatch'
    _title: 'Patch'
  requirements:
    _permission: 'export configuration'

config_patch.settings:
  path: '/admin/config/development/config_patch'
  defaults:
    _form: '\Drupal\config_patch\Form\ConfigPatchSettings'
    _title: 'Config Patch Settings'
  requirements:
    _permission: 'administer config_patch'

config_patch.clear_cache:
  path: '/admin/config/development/config_patch/clear-cache'
  defaults:
    _controller: '\Drupal\config_patch\Controller\ConfigPatchUtilities::clearCache'
  requirements:
    _permission: 'export configuration'

config_patch.toolbar:
  path: '/admin/config/development/config_patch/toolbar'
  defaults:
    _controller: '\Drupal\config_patch\Controller\ConfigPatchToolbar::toolbarAjax'
  requirements:
    _permission: 'export configuration'

config_patch.revert:
  path: '/admin/config/development/config_patch/revert/{config_names}'
  defaults:
    _form: '\Drupal\config_patch\Form\ConfirmRevertForm'
    _title: 'Confirm Revert'
  requirements:
    _permission: 'import configuration'