name: 'Config Patch'
type: module
description: 'Create patches from configuration diffs'
core_version_requirement: ^10 || ^11
package: 'Config'
configure: config_patch.settings

# Information added by Drupal.org packaging script on 2025-06-23
version: '3.0.6'
project: 'config_patch'
datestamp: 1750680252
