patreon_extras.settings:
  type: config_object
  label: 'Patreon extras settings'
  mapping:
    patreon_extras_pledge_data_last_update:
      type: timestamp
      label: 'The late time the pledge data was updated'
    patreon_extras_pledge_count:
      type: integer
      label: 'The pledge count'
    patreon_extras_pledge_amount:
      type: float
      label: 'The amount pledged'